/** @type {import('tailwindcss').Config} */

const designTokens = {
  colors: {
    // Refined indigo — one ownable brand hue (Linear/Vercel register), replacing stock sky.
    primary: {
      50: '#eef2ff',
      100: '#e0e7ff',
      200: '#c7d2fe',
      300: '#a5b4fc',
      400: '#818cf8',
      500: '#6366f1',
      600: '#4f46e5',
      700: '#4338ca',
      800: '#3730a3',
      900: '#312e81',
      950: '#1e1b4b',
    },
    secondary: {
      50: '#fdf4ff',
      100: '#fae8ff',
      200: '#f5d0fe',
      300: '#f0abfc',
      400: '#e879f9',
      500: '#d946ef',
      600: '#c026d3',
      700: '#a21caf',
      800: '#86198f',
      900: '#701a75',
      950: '#4a044e',
    },
    accent: {
      50: '#fff7ed',
      100: '#ffedd5',
      200: '#fed7aa',
      300: '#fdba74',
      400: '#fb923c',
      500: '#f97316',
      600: '#ea580c',
      700: '#c2410c',
      800: '#9a3412',
      900: '#7c2d12',
      950: '#431407',
    },
    // Cool slate-tinted neutrals — designed, not default cold gray.
    neutral: {
      0: '#ffffff',
      50: '#f8fafc',
      100: '#f1f5f9',
      200: '#e2e8f0',
      300: '#cbd5e1',
      400: '#94a3b8',
      500: '#64748b',
      600: '#475569',
      700: '#334155',
      800: '#1e293b',
      900: '#0f172a',
      950: '#020617',
    },
    semantic: {
      success: {
        light: '#34d399',
        DEFAULT: '#10b981',
        dark: '#059669',
      },
      warning: {
        light: '#fbbf24',
        DEFAULT: '#f59e0b',
        dark: '#d97706',
      },
      error: {
        light: '#fca5a5',
        DEFAULT: '#ef4444',
        dark: '#dc2626',
      },
      info: {
        light: '#60a5fa',
        DEFAULT: '#3b82f6',
        dark: '#2563eb',
      },
    },
    dark: {
      bg: '#020617',
      bgSecondary: '#0b1120',
      bgTertiary: '#0f172a',
      card: '#0b1120',
      cardHover: '#0f172a',
      border: '#1e293b',
      borderHover: '#334155',
      text: '#f8fafc',
      textSecondary: '#94a3b8',
      textMuted: '#64748b',
    },
    light: {
      bg: '#ffffff',
      bgSecondary: '#f8fafc',
      bgTertiary: '#f1f5f9',
      card: '#ffffff',
      cardHover: '#f8fafc',
      border: '#e2e8f0',
      borderHover: '#cbd5e1',
      text: '#0f172a',
      textSecondary: '#475569',
      textMuted: '#64748b',
    },
    // Restrained: primary → deep primary / primary → slate. No 3-stop rainbow.
    gradient: {
      primary: 'linear-gradient(135deg, #6366f1 0%, #4f46e5 100%)',
      secondary: 'linear-gradient(135deg, #4f46e5 0%, #0f172a 100%)',
      dark: 'linear-gradient(135deg, #020617 0%, #0f172a 100%)',
      mesh: 'linear-gradient(135deg, #6366f1 0%, #4f46e5 55%, #0f172a 100%)',
    },
  },
  typography: {
    fontFamily: {
      sans: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
      mono: ['JetBrains Mono', 'Fira Code', 'Consolas', 'monospace'],
      display: ['Poppins', 'Inter', 'system-ui', 'sans-serif'],
    },
    fontSize: {
      xs: ['0.75rem', { lineHeight: '1.5' }],
      sm: ['0.875rem', { lineHeight: '1.5' }],
      base: ['1rem', { lineHeight: '1.6' }],
      lg: ['1.125rem', { lineHeight: '1.6' }],
      xl: ['1.25rem', { lineHeight: '1.5' }],
      '2xl': ['1.5rem', { lineHeight: '1.4' }],
      '3xl': ['1.875rem', { lineHeight: '1.3' }],
      '4xl': ['2.25rem', { lineHeight: '1.2' }],
      '5xl': ['3rem', { lineHeight: '1.15' }],
      '6xl': ['3.75rem', { lineHeight: '1.1' }],
      '7xl': ['4.5rem', { lineHeight: '1.1' }],
      '8xl': ['6rem', { lineHeight: '1.05' }],
      '9xl': ['8rem', { lineHeight: '1' }],
      display: ['clamp(3rem, 8vw, 6rem)', { lineHeight: '1.1' }],
      h1: ['clamp(2.5rem, 5vw, 4rem)', { lineHeight: '1.15' }],
      h2: ['clamp(2rem, 4vw, 3rem)', { lineHeight: '1.2' }],
      h3: ['1.5rem', { lineHeight: '1.3' }],
      h4: ['1.25rem', { lineHeight: '1.4' }],
      body: ['1rem', { lineHeight: '1.6' }],
      bodyLg: ['1.125rem', { lineHeight: '1.6' }],
      small: ['0.875rem', { lineHeight: '1.5' }],
      tiny: ['0.75rem', { lineHeight: '1.5' }],
    },
    fontWeight: {
      thin: '100',
      extralight: '200',
      light: '300',
      normal: '400',
      medium: '500',
      semibold: '600',
      bold: '700',
      extrabold: '800',
      black: '900',
    },
    letterSpacing: {
      tighter: '-0.05em',
      tight: '-0.025em',
      normal: '0',
      wide: '0.025em',
      wider: '0.05em',
      widest: '0.1em',
    },
    lineHeight: {
      none: '1',
      tight: '1.1',
      snug: '1.2',
      normal: '1.5',
      relaxed: '1.625',
      loose: '2',
    },
  },
  borderRadius: {
    none: '0',
    xs: '0.125rem',
    sm: '0.25rem',
    DEFAULT: '0.375rem',
    md: '0.5rem',
    lg: '0.75rem',
    xl: '1rem',
    '2xl': '1.5rem',
    '3xl': '2rem',
    full: '9999px',
    button: '0.5rem',
    card: '1rem',
    modal: '1.5rem',
    input: '0.5rem',
    badge: '9999px',
  },
  shadows: {
    none: 'none',
    xs: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
    sm: '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
    DEFAULT: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
    md: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
    lg: '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
    xl: '0 25px 50px -12px rgb(0 0 0 / 0.25)',
    '2xl': '0 35px 60px -15px rgb(0 0 0 / 0.3)',
    inner: 'inset 0 2px 4px 0 rgb(0 0 0 / 0.05)',
    outline: '0 0 0 3px rgb(99 102 241 / 0.4)',
    focus: '0 0 0 3px rgb(99 102 241 / 0.4)',
    colored: {
      primary: '0 10px 40px -10px rgb(99 102 241 / 0.5)',
      secondary: '0 10px 40px -10px rgb(217 70 239 / 0.5)',
      accent: '0 10px 40px -10px rgb(249 115 22 / 0.5)',
      success: '0 10px 40px -10px rgb(16 185 129 / 0.5)',
      warning: '0 10px 40px -10px rgb(245 158 11 / 0.5)',
      error: '0 10px 40px -10px rgb(239 68 68 / 0.5)',
    },
    glow: {
      sm: '0 0 10px rgb(99 102 241 / 0.3)',
      DEFAULT: '0 0 20px rgb(99 102 241 / 0.4)',
      lg: '0 0 40px rgb(99 102 241 / 0.5)',
      xl: '0 0 60px rgb(99 102 241 / 0.6)',
    },
  },
  zIndex: {
    auto: 'auto',
    0: '0',
    10: '10',
    20: '20',
    30: '30',
    40: '40',
    50: '50',
    dropdown: '100',
    sticky: '200',
    fixed: '300',
    modalBackdrop: '400',
    modal: '500',
    popover: '600',
    tooltip: '700',
    toast: '800',
    max: '9999',
  },
  transitions: {
    duration: {
      instant: '0ms',
      fastest: '50ms',
      fast: '100ms',
      normal: '200ms',
      slow: '300ms',
      slower: '500ms',
      slowest: '700ms',
      modal: '300ms',
      toast: '400ms',
      tooltip: '200ms',
    },
    easing: {
      linear: 'linear',
      in: 'cubic-bezier(0.4, 0, 1, 1)',
      out: 'cubic-bezier(0, 0, 0.2, 1)',
      inOut: 'cubic-bezier(0.4, 0, 0.2, 1)',
      easeOutExpo: 'cubic-bezier(0.19, 1, 0.22, 1)',
      easeInOutExpo: 'cubic-bezier(0.87, 0, 0.13, 1)',
      easeOutBack: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      easeInOutBack: 'cubic-bezier(0.68, -0.55, 0.27, 1.55)',
      bounce: 'cubic-bezier(0.68, -0.55, 0.27, 1.55)',
      spring: 'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
    },
    property: {
      all: 'all',
      colors: 'color, background-color, border-color, text-decoration-color, fill, stroke',
      opacity: 'opacity',
      shadow: 'box-shadow',
      transform: 'transform',
      width: 'width',
      height: 'height',
      spacing: 'margin, padding',
    },
  },
  breakpoints: {
    xs: '320px',
    sm: '640px',
    md: '768px',
    lg: '1024px',
    xl: '1280px',
    '2xl': '1536px',
    '3xl': '1920px',
  },
  container: {
    sm: '640px',
    md: '768px',
    lg: '1024px',
    xl: '1280px',
    '2xl': '1536px',
    full: '100%',
  },
  opacity: {
    0: '0',
    5: '0.05',
    10: '0.1',
    20: '0.2',
    25: '0.25',
    30: '0.3',
    40: '0.4',
    50: '0.5',
    60: '0.6',
    70: '0.7',
    75: '0.75',
    80: '0.8',
    90: '0.9',
    95: '0.95',
    100: '1',
  },
  blur: {
    none: '0',
    sm: '4px',
    DEFAULT: '8px',
    md: '12px',
    lg: '16px',
    xl: '24px',
    '2xl': '40px',
    '3xl': '64px',
  },
  backdropBlur: {
    none: '0',
    sm: '4px',
    DEFAULT: '8px',
    md: '12px',
    lg: '16px',
    xl: '24px',
    '2xl': '40px',
    '3xl': '64px',
  },
  animation: {
    none: 'none',
    spin: 'spin 1s linear infinite',
    ping: 'ping 1s cubic-bezier(0, 0, 0.2, 1) infinite',
    pulse: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
    bounce: 'bounce 1s infinite',
    wiggle: 'wiggle 1s ease-in-out infinite',
    shimmer: 'shimmer 2s linear infinite',
    fadeIn: 'fadeIn 200ms ease-out',
    fadeOut: 'fadeOut 200ms ease-in',
    slideIn: 'slideIn 300ms ease-out',
    slideOut: 'slideOut 300ms ease-in',
    scaleIn: 'scaleIn 200ms ease-out',
    scaleOut: 'scaleOut 200ms ease-in',
  },
  keyframes: {
    fadeIn: {
      '0%': { opacity: '0' },
      '100%': { opacity: '1' },
    },
    fadeOut: {
      '0%': { opacity: '1' },
      '100%': { opacity: '0' },
    },
    slideIn: {
      '0%': { transform: 'translateY(10px)', opacity: '0' },
      '100%': { transform: 'translateY(0)', opacity: '1' },
    },
    slideOut: {
      '0%': { transform: 'translateY(0)', opacity: '1' },
      '100%': { transform: 'translateY(-10px)', opacity: '0' },
    },
    scaleIn: {
      '0%': { transform: 'scale(0.95)', opacity: '0' },
      '100%': { transform: 'scale(1)', opacity: '1' },
    },
    scaleOut: {
      '0%': { transform: 'scale(1)', opacity: '1' },
      '100%': { transform: 'scale(0.95)', opacity: '0' },
    },
    spin: {
      '0%': { transform: 'rotate(0deg)' },
      '100%': { transform: 'rotate(360deg)' },
    },
    ping: {
      '75%, 100%': { transform: 'scale(2)', opacity: '0' },
    },
    pulse: {
      '0%, 100%': { opacity: '1' },
      '50%': { opacity: '0.5' },
    },
    bounce: {
      '0%, 100%': { transform: 'translateY(-25%)', animationTimingFunction: 'cubic-bezier(0.8, 0, 1, 1)' },
      '50%': { transform: 'translateY(0)', animationTimingFunction: 'cubic-bezier(0, 0, 0.2, 1)' },
    },
    wiggle: {
      '0%, 100%': { transform: 'rotate(-3deg)' },
      '50%': { transform: 'rotate(3deg)' },
    },
    shimmer: {
      '0%': { backgroundPosition: '200% 0' },
      '100%': { backgroundPosition: '-200% 0' },
    },
  },
};

export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      animation: {
        'gradient-x': 'gradient-x 15s ease infinite',
        'gradient-y': 'gradient-y 15s ease infinite',
        'gradient-xy': 'gradient-xy 15s ease infinite',
        'fade-in': 'fadeIn 0.5s ease-out',
        'fade-out': 'fadeOut 0.5s ease-in',
        'slide-in-from-top': 'slideInFromTop 0.3s ease-out',
        'slide-in-from-top-2': 'slideInFromTop2 0.2s ease-out',
        'slide-in-from-bottom': 'slideInFromBottom 0.3s ease-out',
        'slide-in-from-left': 'slideInFromLeft 0.3s ease-out',
        'slide-in-from-right': 'slideInFromRight 0.3s ease-out',
        'slide-out-to-top': 'slideOutToTop 0.3s ease-in',
        'slide-out-to-bottom': 'slideOutToBottom 0.3s ease-in',
        'slide-out-to-left': 'slideOutToLeft 0.3s ease-in',
        'slide-out-to-right': 'slideOutToRight 0.3s ease-in',
        'scale-in': 'scaleIn 0.2s ease-out',
        'scale-out': 'scaleOut 0.2s ease-in',
        'bounce-slow': 'bounce 3s infinite',
        'pulse-slow': 'pulse 4s infinite',
        'spin-slow': 'spin 8s linear infinite',
        'spin-reverse': 'spinReverse 8s linear infinite',
        'wiggle': 'wiggle 1s ease-in-out infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'float': 'float 6s ease-in-out infinite',
        'float-delayed': 'float 6s ease-in-out infinite 3s',
        'pulse-glow': 'pulseGlow 2s ease-in-out infinite',
        'rotate-slow': 'rotateSlow 20s linear infinite',
        'orbit': 'orbit 20s linear infinite',
        'orbit-reverse': 'orbitReverse 20s linear infinite',
      },
      keyframes: {
        'gradient-x': {
          '0%, 100%': {
            'background-size': '200% 200%',
            'background-position': 'left center',
          },
          '50%': {
            'background-size': '200% 200%',
            'background-position': 'right center',
          },
        },
        'gradient-y': {
          '0%, 100%': {
            'background-size': '200% 200%',
            'background-position': 'center top',
          },
          '50%': {
            'background-size': '200% 200%',
            'background-position': 'center bottom',
          },
        },
        'gradient-xy': {
          '0%, 100%': {
            'background-size': '400% 400%',
            'background-position': 'left top',
          },
          '50%': {
            'background-size': '400% 400%',
            'background-position': 'right bottom',
          },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeOut: {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        slideInFromTop: {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideInFromTop2: {
          '0%': { transform: 'translateY(-5px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideInFromBottom: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideInFromLeft: {
          '0%': { transform: 'translateX(-10px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        slideInFromRight: {
          '0%': { transform: 'translateX(10px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        slideOutToTop: {
          '0%': { transform: 'translateY(0)', opacity: '1' },
          '100%': { transform: 'translateY(-10px)', opacity: '0' },
        },
        slideOutToBottom: {
          '0%': { transform: 'translateY(0)', opacity: '1' },
          '100%': { transform: 'translateY(10px)', opacity: '0' },
        },
        slideOutToLeft: {
          '0%': { transform: 'translateX(0)', opacity: '1' },
          '100%': { transform: 'translateX(-10px)', opacity: '0' },
        },
        slideOutToRight: {
          '0%': { transform: 'translateX(0)', opacity: '1' },
          '100%': { transform: 'translateX(10px)', opacity: '0' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        scaleOut: {
          '0%': { transform: 'scale(1)', opacity: '1' },
          '100%': { transform: 'scale(0.95)', opacity: '0' },
        },
        wiggle: {
          '0%, 100%': { transform: 'rotate(-3deg)' },
          '50%': { transform: 'rotate(3deg)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '200% 0' },
          '100%': { backgroundPosition: '-200% 0' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        pulseGlow: {
          '0%, 100%': { boxShadow: '0 0 20px -5px rgb(99 102 241 / 0.4)' },
          '50%': { boxShadow: '0 0 40px -10px rgb(99 102 241 / 0.6)' },
        },
        rotateSlow: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
        orbit: {
          '0%': { transform: 'rotate(0deg) translateX(100px) rotate(0deg)' },
          '100%': { transform: 'rotate(360deg) translateX(100px) rotate(-360deg)' },
        },
        orbitReverse: {
          '0%': { transform: 'rotate(0deg) translateX(100px) rotate(0deg)' },
          '100%': { transform: 'rotate(-360deg) translateX(100px) rotate(360deg)' },
        },
      },
      colors: {
        primary: designTokens.colors.primary,
        secondary: designTokens.colors.secondary,
        accent: designTokens.colors.accent,
        neutral: designTokens.colors.neutral,
        success: {
          light: designTokens.colors.semantic.success.light,
          DEFAULT: designTokens.colors.semantic.success.DEFAULT,
          dark: designTokens.colors.semantic.success.dark,
        },
        warning: {
          light: designTokens.colors.semantic.warning.light,
          DEFAULT: designTokens.colors.semantic.warning.DEFAULT,
          dark: designTokens.colors.semantic.warning.dark,
        },
        error: {
          light: designTokens.colors.semantic.error.light,
          DEFAULT: designTokens.colors.semantic.error.DEFAULT,
          dark: designTokens.colors.semantic.error.dark,
        },
        info: {
          light: designTokens.colors.semantic.info.light,
          DEFAULT: designTokens.colors.semantic.info.DEFAULT,
          dark: designTokens.colors.semantic.info.dark,
        },
        dark: designTokens.colors.dark,
        light: designTokens.colors.light,
        gradient: designTokens.colors.gradient,
        semantic: designTokens.colors.semantic,
      },
      fontFamily: {
        sans: designTokens.typography.fontFamily.sans,
        mono: designTokens.typography.fontFamily.mono,
        display: designTokens.typography.fontFamily.display,
        heading: designTokens.typography.fontFamily.sans,
      },
      fontSize: {
        xs: designTokens.typography.fontSize.xs,
        sm: designTokens.typography.fontSize.sm,
        base: designTokens.typography.fontSize.base,
        lg: designTokens.typography.fontSize.lg,
        xl: designTokens.typography.fontSize.xl,
        '2xl': designTokens.typography.fontSize['2xl'],
        '3xl': designTokens.typography.fontSize['3xl'],
        '4xl': designTokens.typography.fontSize['4xl'],
        '5xl': designTokens.typography.fontSize['5xl'],
        '6xl': designTokens.typography.fontSize['6xl'],
        '7xl': designTokens.typography.fontSize['7xl'],
        '8xl': designTokens.typography.fontSize['8xl'],
        '9xl': designTokens.typography.fontSize['9xl'],
        display: designTokens.typography.fontSize.display,
        h1: designTokens.typography.fontSize.h1,
        h2: designTokens.typography.fontSize.h2,
        h3: designTokens.typography.fontSize.h3,
        h4: designTokens.typography.fontSize.h4,
        body: designTokens.typography.fontSize.body,
        'body-lg': designTokens.typography.fontSize.bodyLg,
        small: designTokens.typography.fontSize.small,
        tiny: designTokens.typography.fontSize.tiny,
      },
      fontWeight: designTokens.typography.fontWeight,
      letterSpacing: designTokens.typography.letterSpacing,
      lineHeight: designTokens.typography.lineHeight,
      spacing: designTokens.spacing,
      borderRadius: designTokens.borderRadius,
      boxShadow: designTokens.shadows,
      zIndex: designTokens.zIndex,
      transitionDuration: designTokens.transitions.duration,
      transitionTimingFunction: designTokens.transitions.easing,
      transitionProperty: designTokens.transitions.property,
      screens: designTokens.breakpoints,
      container: {
        center: true,
        padding: '1.5rem',
        screens: designTokens.container,
      },
      opacity: designTokens.opacity,
      blur: designTokens.blur,
      backdropBlur: designTokens.backdropBlur,
      backgroundImage: {
        'gradient-primary': designTokens.colors.gradient.primary,
        'gradient-secondary': designTokens.colors.gradient.secondary,
        'gradient-dark': designTokens.colors.gradient.dark,
        'gradient-mesh': designTokens.colors.gradient.mesh,
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        'mesh-gradient': 'radial-gradient(ellipse at center, var(--tw-gradient-stops))',
        'noise': "url(\"data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)'/%3E%3C/svg%3E\")",
      },
      backgroundSize: {
        '300%': '300%',
      },
      scale: {
        '102': '1.02',
        '103': '1.03',
        '98': '0.98',
        '97': '0.97',
      },
      rotate: {
        '3': '3deg',
        '-3': '-3deg',
        '6': '6deg',
        '-6': '-6deg',
        '12': '12deg',
        '-12': '-12deg',
      },
      translate: {
        '1/8': '12.5%',
        '3/8': '37.5%',
        '5/8': '62.5%',
        '7/8': '87.5%',
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
  safelist: [
    { pattern: /bg-(primary|secondary|accent|neutral|success|warning|error|info)-(50|100|200|300|400|500|600|700|800|900|950)/ },
    { pattern: /text-(primary|secondary|accent|neutral|success|warning|error|info)-(50|100|200|300|400|500|600|700|800|900|950)/ },
    { pattern: /border-(primary|secondary|accent|neutral|success|warning|error|info)-(50|100|200|300|400|500|600|700|800|900|950)/ },
    { pattern: /hover:bg-(primary|secondary|accent|neutral|success|warning|error|info)-(50|100|200|300|400|500|600|700|800|900|950)/ },
    { pattern: /hover:text-(primary|secondary|accent|neutral|success|warning|error|info)-(50|100|200|300|400|500|600|700|800|900|950)/ },
    { pattern: /dark:bg-(primary|secondary|accent|neutral|success|warning|error|info)-(50|100|200|300|400|500|600|700|800|900|950)/ },
    { pattern: /dark:text-(primary|secondary|accent|neutral|success|warning|error|info)-(50|100|200|300|400|500|600|700|800|900|950)/ },
    { pattern: /dark:border-(primary|secondary|accent|neutral|success|warning|error|info)-(50|100|200|300|400|500|600|700|800|900|950)/ },
    'animate-gradient-x',
    'animate-gradient-y',
    'animate-gradient-xy',
    'animate-float',
    'animate-float-delayed',
    'animate-pulse-glow',
    'animate-rotate-slow',
    'animate-orbit',
    'animate-orbit-reverse',
    'animate-shimmer',
  ],
};